version: '3'

volumes:
  mysql-volume: {}
  redis-volume: {}
  data-volume: {}

services:
  front:
    container_name: cms-front
    build:
      context: frontend
      dockerfile: front.dev.Dockerfile
    image: cms-img-front
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./data:/app/src/assets/data

  flask:
    container_name: cms-flask
    env_file:
      - flask/.env.dev
      - worker/.env
    build:
      context: flask
      dockerfile: flask.dev.Dockerfile
    image: cms-img-flask
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./flask:/app:delegated
      - ./data:/data:z
    depends_on:
      - db
      - redis

  db:
    container_name: cms-mysql
    build:
      context: db
      dockerfile: db.dev.Dockerfile
    image: cms-img-mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    expose:
      - 3306
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    container_name: cms-redis
    env_file:
      - redis/.env
    build:
      context: redis
      dockerfile: redis.dev.Dockerfile
    image: cms-img-redis
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379
    healthcheck:
      test: "redis-cli -h 127.0.0.1 ping"
      interval: 3s
      timeout: 1s
      retries: 5

  worker:
    container_name: cms-worker
    env_file:
      - worker/.env
    build:
      context: worker
      dockerfile: worker.dev.Dockerfile
    image: cms-img-worker
    depends_on:
      - redis
    volumes:
      - ./worker:/worker
      - ./data:/data:z
  media:
    container_name: cms-media
    #env_file:
    #  - media/.env
    build:
      context: media
      dockerfile: media.dev.Dockerfile
    image: cms-img-media
    expose:
      - 8080
      - 1935
    ports:
      - 8081:8080
      - 1935:1935
    volumes:
    - ./media/volume:/volume